### PR TITLE
fix build issue with wrong names

### PR DESCRIPTION
**Pull request by voronianski**
There was variance in `./lib` file names and imports of `index.css` which leads to build errors. This update fixes it, could you please publish it to npm ASAP? Thanks!

### CODE REVIEW

**Comment by jxnblk** [comment]
Are you using rework or some other processor?

**Comment by jxnblk** [comment]
Omitting the file extension is the correct syntax for rework-npm, so I won't be merging this. Please open an issue if you're having problems.

**Comment by voronianski** [comment]
@jxnblk then please make an update which omits extension with both files, that's what I have when installing this package:



No surprise that leads to compile errors:

```bash
error · Error: Failed to find ./lib/margins
    from /Users/dmitri/github/bassmyth/node_modules/basscss-utility-white-space/index.css
    in [
        /Users/dmitri/github/bassmyth/node_modules/basscss-utility-white-space,
        /Users/dmitri/github/bassmyth/myth
    ]
```

**Comment by voronianski** [comment]
@jxnblk I'm using [myth](http://www.myth.io/) to build files (which is built with Rework). 

I see the same problem with omitted file extensions in - https://github.com/jxnblk/basscss-grid/blob/master/index.css#L3

It looks like myth won't find a file if there's no extension.. is it really necessary to omit them?

**Comment by jxnblk** [comment]
Can you make sure you have the latest version (0.0.3 )of the module? I think the file extension has been fixed.

As for the imports, Basscss uses rework-npm not rework-import. Last time I checked the latter did not support some of the features that basscss is using. I think you can use the rework-npm plugin with myth, but I'd have to check.

Can you open an issue for myth support in the meantime?

**Comment by voronianski** [comment]
@jxnblk I have `0.0.3` version of the module.

I'll create an issue for myth guys, thanks!

**Comment by voronianski** [comment]
related - https://github.com/segmentio/myth/issues/120

**Comment by jxnblk** [comment]
Sorry. I meant create an issue on Basscss for myth support.

**Pull request closed without merging**
